name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      uses: iCrawl/action-tsc@v1
      uses: actions/setup-node@v1
      with:
        node-version: 12
      name: yarn install
      run: yarn install
      name: tsc
      uses: icrawl/action-tsc@v1

      name: Build
      run: ./build.sh
